apiVersion: apps/v1
kind: Deployment
metadata:
  name: mylamp-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mylamp-pod
  template:
    metadata:
      labels:
        app: mylamp-pod
    spec:
      containers:
      - name: mylamp
        image: registry.cn-hangzhou.aliyuncs.com/fanwb/pat:1.0
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mylamp-service
  namespace: dev
spec:
  selector:
    app: mylamp-pod
  clusterIP: None
  type: ClusterIP
  ports:
  - port: 50080
    targetPort: 80 

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-http-mylamp
  namespace: dev
spec:
  rules:
  - host: mylamp.itheima.com
    http:
      paths:
        - backend:
            service:
              name: mylamp-service
              port:
                number: 50080
          path: /
          pathType: ImplementationSpecific
