name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: 
      name: REPO_PASS
    steps:
    - uses: actions/checkout@v4
    - name: rm github action yml 
      run: rm -rf /.github/workflows/docker-image.yml
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/fanwb/mylamp:11.0
    - name: Run Prisma Cloud 
      id: prisma-cloud
      uses: bridgecrewio/checkov-action@master
      env:
        PRISMA_API_URL: https://api.sg.prismacloud.io
      with:
        api-key: ${{ secrets.BC_API_KEY }}
    - name: login the Docker repo
      run: docker login --username=fanwb.1985@163.com --password=${{ secrets.ALI_REPO_PASS }} registry.cn-hangzhou.aliyuncs.com
    - name: push the Docker image
      run:  docker push registry.cn-hangzhou.aliyuncs.com/fanwb/mylamp:11.0
