name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/fanwb/mylamp:11.0
    - name: push the Docker image
      run: 
        docker login --username=fanwb.1985@163.com --password=suqian3NN registry.cn-hangzhou.aliyuncs.com
        docker push registry.cn-hangzhou.aliyuncs.com/fanwb/mylamp:11.0
